version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    networks:
      - app-tier
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: userApp
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    networks:
      - app-tier
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - app-tier
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  app:
    build: .
    container_name: apps
    networks:
      - app-tier
    ports: 
      - 4040:4040
      - 5050:5050
    expose:
      - 4040
      - 5050
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userApp
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - db
      - kafka
      - zookeeper