version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5600:5672
      - 15670:15672
    expose:
      - 5600
      - 15670
  app:
    build: .
    container_name: app
    ports:
      - 5000:5000
      - 5005:5005
    expose:
      - 5000
      - 5005
    environment:
      - MQ_HOST=rabbitmq
    depends_on:
      - rabbitmq